Prefix: "!"
Client:
    LogLevel: Debug
    MessageCacheSize: 1000
Tokens:
    Discord: token
Owners:
    - ID
AWS:
    AccessKey: key
    SecretKey: key
    Region: eu-west-2
LavaLink:
    RestUri: http://192.168.0.1:2333
    WebSocketUri: ws://192.168.0.1:2333
    Password: "password"